[project]
name = "django-clean-arch-ddd-cqrs-kraken"
version = "0.1.0"
description = ""
authors = [
    {name = "Saul",email = "sondonsaul@gmail.com"}
]
readme = "README.md"
requires-python = ">=3.13,<4.0"
dependencies = [
    "django (>=6.0.2,<7.0.0)",
    "python-dotenv (>=1.2.1,<2.0.0)",
    "djangorestframework (>=3.16.1,<4.0.0)",
    "loguru (>=0.7.3,<0.8.0)"
]
[tool.poetry]
package-mode = false

[tool.pytest.ini_options]
DJANGO_SETTINGS_MODULE = "core.settings"
pythonpath = ["."]
markers = [
    "unit: unit tests",
    "integration: integration tests"
]

[tool.poetry.group.dev.dependencies]
django-stubs = "^5.2.9"
pytest = "^9.0.2"
pytest-django = "^4.11.1"
httpx = "^0.28.1"
factory-boy = "^3.3.3"

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

